name: mc-pathfinding
version: "${project.version}"
main: com.github.btror.mcpathfinding.McPathfinding
api-version: 1.13
authors: [btror]
description: Spigot pathfinding plugin.
website: https://github.com/btror
