name: mc-pathfinding PR Build

on:
  pull_request:

jobs:
  cleanup-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17.0.2
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17.0.2
          server-id: github
          cache: 'maven'

      - name: Check pom.xml Version
        run: |
          git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}
          git diff --quiet ${{ github.base_ref }} -- pom.xml || (echo "pom.xml has changed." && exit 0)
          echo "No changes detected in pom.xml."
          exit 1

      - name: Build with Maven
        run: mvn clean package --file pom.xml
