name: Build and Upload

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      uses: actions/checkout@v3

      - name: JDK setup
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17.0.2
          server-id: github
          cache: 'maven'

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: |
          mvn package --file pom.xml

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: mc-pathfinding
          path: mc-pathfinding/target/mc-pathfinding.jar