name: Build and Upload

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        uses: actions/checkout@v3
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: JDK setup
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17.0.2
          server-id: github
          cache: 'maven'

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: |
          mvn package --file pom.xml

      - name: Capture Maven Version
        id: maven_version
        run: |
          MAVEN_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "maven version ${MAVEN_VERSION}"
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: mc-pathfinding
          path: /home/runner/work/mc-pathfinding/mc-pathfinding/target/mc-pathfinding-${{ steps.maven_version.outputs.MAVEN_VERSION }}.jar

      - name: Create Release
        if: success()
        run: |
          git config --global user.name ${{ secrets.GIT_USERNAME }}
          git config --global user.email ${{ secrets.GIT_EMAIL }}
          MAVEN_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "creating tag ${MAVEN_VERSION}"
          git tag -a "${MAVEN_VERSION}" -m "Version ${MAVEN_VERSION}"
          git push origin "${MAVEN_VERSION}"
