name: Build and Upload

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        uses: actions/checkout@v3

      - name: JDK setup
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17.0.2
          server-id: github
          cache: 'maven'

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      #      - name: Install xmllint
      #        run: |
      #          sudo apt-get update -q
      #          sudo apt-get install -y libxml2-utils

      - name: Build with Maven
        run: |
          mvn package --file pom.xml

      - name: Extract Maven Version
        id: maven_version
        run: |
          MAVEN_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) >> $GITHUB_ENV
          echo "MAVEN_VERSION=${MAVEN_VERSION}"

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: mc-pathfinding
          run: echo "${{ env.MAVEN_VERSION }}"
          path: mc-pathfinding/target/mc-pathfinding-${{ env.MAVEN_VERSION }}.jar
#          path: mc-pathfinding/out/artifacts/mc_pathfinding_jar/mc-pathfinding.jar
